CobeyH/SENG-480A

- frontend/src/firebase.tsx
Works about the same as Firestore.
> Changed auth to use realtime-db

- frontend/src/App.tsx
- frontend/src/pages/Groups.tsx
> added groups

- frontend/.eslintrc.json
- frontend/.husky/pre-commit
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/ColorModeSwitcher.tsx
- frontend/src/firebase.tsx
- frontend/src/index.tsx
- frontend/src/pages/CreateGroup.tsx
- frontend/src/pages/GroupPage.tsx
- frontend/src/pages/Groups.tsx
- frontend/src/pages/Registration.tsx
- frontend/src/pages/RidePage.tsx
- frontend/src/reportWebVitals.ts
- frontend/src/serviceWorker.ts
- frontend/src/setupTests.ts
- frontend/src/test-utils.tsx
Adding prettier and eslint into the workflow. Prettier has been integrated with eslint-config-prettier and runs in a pre-commit hook using Husky and lint-staged. This means that files will be automatically formatted when they are committed using git. Resolved #35
> Auto Formatting

- frontend/src/App.tsx
- frontend/src/pages/CreateGroup.tsx
- frontend/src/pages/GroupPage.tsx
- frontend/src/pages/GroupsListPage.tsx
- frontend/src/pages/JoinGroup.tsx
Currently no way to join a group which is why it is a draft. No clue how we want to handle joining groups for demo.
> Users in groups

- frontend/src/firebase.tsx
- frontend/src/pages/LoginPage.tsx
- frontend/src/pages/Registration.tsx
Adding functionality for registration/login using email and password. Chakra forms break the firebase functions so the forms are ugly for now. Resolves #25
> Email login

- frontend/.eslintrc.json
Fixes the lint error in Windows system. Not sure if it's going to cause any issue in other systems
> Added rule in eslintrc

- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/LoginPage.tsx
- frontend/src/pages/Registration.tsx
Fixed the submission error in login and registration pages. TBH I basically tried to implement UIs again and it just worked this time? So I'm not sure what caused the initial error lol
> Fixed login & registration page

- frontend/package-lock.json
- frontend/package.json
- frontend/src/firebase.tsx
- frontend/src/pages/CreateGroup.tsx
- frontend/src/pages/GroupPage.tsx
- frontend/src/pages/Header.tsx
- frontend/src/storage.tsx
Adding a description property to groups to describe what the group is for. Description is added to the database and displayed on the group page.
Also doing some style cleanup (padding/layout) with the header.
Resolved #58
> Group description

- frontend/src/components/Header.tsx
Simple PR for adding the users name to the header so that you can see who is currently logged in.
Resolves #83
> CH: Adding user's name to header

- frontend/src/App.tsx
- frontend/src/NavigationConstants.ts
- frontend/src/components/Header.tsx
- frontend/src/components/MapView.tsx
- frontend/src/pages/CreateGroup.tsx
- frontend/src/pages/JoinGroup.tsx
- frontend/src/pages/LoginPage.tsx
- frontend/src/pages/Registration.tsx
still has spoooooky error
Resolves #64  #47
> Join group redirect

- frontend/src/pages/GroupsListPage.tsx
> added seach groups

- frontend/src/pages/GroupsListPage.tsx
- frontend/src/pages/LoginPage.tsx
- frontend/src/pages/Registration.tsx
> font colours changed for groupslist, login, registration

- frontend/src/components/ShareLink.tsx
- frontend/src/pages/GroupPage.tsx
- frontend/src/pages/GroupsListPage.tsx
- frontend/src/theme/colours.tsx
Resolving various style issues.
Resolved #111 #114 
The styling of the group list page isn't perfect. Needs a bit of work from #110
> Cobey style fixes

- frontend/src/pages/GroupsListPage.tsx
> increased margin in group list page

- frontend/src/pages/LoginPage.tsx
- frontend/src/pages/Registration.tsx
- frontend/src/theme/style.tsx
Login and registration pages are now blue, but its done by just changing the color of the container.
resolves #112
> Login page and Registration are now blue, all the other pages are white

- frontend/src/components/MapView.tsx
- frontend/src/components/RideCard.tsx
- frontend/src/pages/CreateRide.tsx
Drag map markers around on Create and open and close RideCards on Group Page.
> Fix map zoom in Create and RideCard

- frontend/src/components/GroupJoinButton.tsx
- frontend/src/components/GroupSearch.tsx
- frontend/src/pages/CreateGroup.tsx
- frontend/src/pages/GroupsListPage.tsx
- frontend/src/pages/JoinGroup.tsx
Resolved #89 
Resolved #65 
- Added a "private group" checkbox on group creation.
- Added functionality to the search box on the group list page. Users can search for groups and join groups from a list.
- Moved the group joining functionality to a separate component.
> Private groups

- .gitignore
- README.md
- frontend/firebase.json
- frontend/package.json
- frontend/src/firebase.tsx
- frontend/src/storage.tsx
- frontend/storage.rules
Setting up database, storage and authentication emulators when the code is running locally. No data has been pre-loaded into the local database or authentication at this point.
Resolved #144
> Firebase Emulators

- frontend/src/pages/CreateRide.tsx
Minor change to the ride creation. I removed the two "create as driver", "create as passenger" buttons and replaced it with a checkbox that can be toggled if they are the driver.
> Ride creation cleanup

- frontend/src/App.tsx
- frontend/src/components/SignInRegister.tsx
- frontend/src/pages/JoinGroup.tsx
- frontend/src/pages/LoginPage.tsx
Closes #117.
Feedback on UI/UX welcome in comments.
> Join Group now offers Sign In or Register

- frontend/src/components/AddCar.tsx
- frontend/src/components/Header.tsx
- frontend/src/firebase.tsx
- frontend/src/theme/colours.tsx
- Converted the profile menu to a drop-down menu
- Added a new section in the drop-down menu to add a car to your profile.
- Cars are currently hard-coded options. In the future we could use some sort of car selection API to get more realistic fuel statistics.
Resolves #153
> Driver cars

- frontend/src/components/AddCar.tsx
- frontend/src/components/CarStatsSlider.tsx
- frontend/src/components/ChooseCar.tsx
- frontend/src/components/GroupSearch.tsx
- frontend/src/pages/CreateRide.tsx
Adds the ability for drivers to select a car from their profile when they create a ride. 
Resolves #156
> Car selection

- .gitignore
- frontend/package.json
Making data persist between stopping and starting the Firebase emulators. This should alleviate the problem of needing to create new data every time the application starts.
Resolved #162
> Persistent Emulator Data

- frontend/src/components/RideCard.tsx
- frontend/src/pages/CreateRide.tsx
Had a messy conflict issue, so I decided to just create another PR.
Resolves #141
> Made a new PR for ride time

- frontend/src/components/GroupMembersList.tsx
- frontend/src/components/RideCard.tsx
- frontend/src/pages/CreateGroup.tsx
- frontend/src/pages/GroupPage.tsx
The person that creates the group is now automatically designated as the group owner.
A group members list is now available in each group.
The owner of the group is tagged with a label.
Resolves #92
> Group owner

- frontend/src/components/RideCard.tsx
Ride time is now displayed correctly.
Resolves #178
> Fixed ride time display bug

- frontend/src/components/Chat.tsx
- frontend/src/components/GroupDrawer.tsx
- frontend/src/components/GroupMembersList.tsx
- frontend/src/firebase/database.tsx
- frontend/src/pages/GroupPage.tsx
Moving the chat to the group drawer.
Refactoring the drawer to allow for future additions.
Restyling the chat.
> Chat styling

- frontend/src/components/FileDropzone.tsx
- frontend/src/firebase/database.tsx
- frontend/src/firebase/storage.tsx
- frontend/src/pages/CreateGroup.tsx
- frontend/src/pages/GroupsListPage.tsx
Resolves #66 
Refactoring banner code to accept generic photo uploads to various locations.
Adding an option to upload a group profile picture when the group is created.
Making the file Dropzones less ugly using Chakra components.
Profile pictures are displayed in the group list page.
> Group profile pics

- frontend/src/components/Chat.tsx
> Chat inbox now on the bottom

- frontend/src/components/RideCard.tsx
- frontend/src/firebase/database.tsx
- frontend/src/pages/CreateRide.tsx
Resolves #201
Allows users to select their current position as a start point instead of clicking on the map.
Also removed the "end time" from rides.
> Current Location Pickups

- README.md
- frontend/package-lock.json
- frontend/package.json
- frontend/src/Directions.tsx
- frontend/src/components/LocationSearch.tsx
- frontend/src/components/RideCard.tsx
- frontend/src/firebase/database.tsx
- frontend/src/pages/CreateRide.tsx
Feature-wise, it's not quite complete but is demo-able
I removed the "current location" feature because it was hard. Will get to if we decide it's important for the demo.
Some UX jank in picking a pickup point where it occurs sooner than you think, I'd like some form of confirmation after the user chooses a point.
I also added a dependency on `chakra-react-select` for the search suggestions. It's based on `react-select` which I've used elsewhere and am a fan of.
> Location search

- frontend/src/pages/ProductPage.tsx
Minor fixes to product page colours
> Product page background fixed for issues with white text

- frontend/src/components/PasswordField.tsx
- frontend/src/pages/LoginPage.tsx
- frontend/src/pages/Registration.tsx
Adding option to show/hide your password on the login and register pages.
Resolves #218
> Adding option to show password

- frontend/package-lock.json
- frontend/package.json
Updating the firebase tools packages to remove the critical vulnerability. 
Also updated the framer package. Resolves #233
> Fixing critical vulnerability in node modules

- frontend/src/Directions.tsx
- frontend/src/components/Rides/AddPickupPoint.tsx
- frontend/src/components/Rides/PickupMarkers.tsx
- frontend/src/components/Rides/RideCard.tsx
- frontend/src/pages/CreateRide.tsx
resolves #221 
It looks like this now
(panda peach is a rider)
> 221 pickup points need padding and labels

- frontend/src/pages/CreateGroup.tsx
> centered create group

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Profiles/AddCar.tsx
- frontend/src/theme/components/text.tsx
- frontend/src/theme/style.tsx
Converting the "Add Car" modal to use a Wizard style. This relies on the Chakra-ui-steps npm package found here ![https://www.npmjs.com/package/chakra-ui-steps] 
I also made the car name required.
Resolves #226
> Require car name

- frontend/src/components/Rides/ChooseCar.tsx
- frontend/src/components/Rides/RideCard.tsx
- frontend/src/components/VerifiedStep.tsx
- frontend/src/pages/CreateRide.tsx
Adding a verified step wrapper that can be used to verify that all required information is provided before a step proceeds.
Also converting the "Create Ride" workflow use a Wizard.
Resolves #228
> Ride Creation Wizard

- frontend/src/components/Promotional/ProductHeader.tsx
- frontend/src/pages/ProductPage.tsx
Making the product page much more responsive to different sized screen.
The header dropdowns now automatically collapse into a hamburger menu when there isn't enough room.
Fixed screen width so you can't scroll sideways on mobile.
Many other responsive improvements and refactoring.
Resolves #249
> Mobile product page

- frontend/src/components/VerifiedStep.tsx
very simple change to allow pressing enter for next when using VerifiedStep
> added enter to go next step

- frontend/src/components/Groups/Chat.tsx
- frontend/src/components/Groups/GroupDrawer.tsx
- frontend/src/firebase/database.tsx
I have no clue why scrollTo(0, 100000000) doesn't scroll to the bottom of the page. 
https://jsfiddle.net/re8sofpy/5/
this works fine.
but for whatever reason, this code does not.
I have spent an embarrassing amount of time on this.
It scrolls almost to the very bottom, but not quite. Any help is appreciated
> Auto scroll chat

- frontend/src/pages/CreateRide.tsx
this should make it super clear what each thing does as well as allow for better time choosing components (I currently think it sucks less than before - but should suck less)
> split choosing dates into two components to makes less of a hassle.

- frontend/src/pages/CreateGroup.tsx
The "Create Group" workflow has been converted to use a Wizard like the "Create Ride" and "Add Car". At this point I haven't fixed any of the other UX issues in the group creation such as feedback when uploading a banner. I will do that after this is merged on a different PR.
Resolves #246
> Turning create group into a wizard

- frontend/src/pages/Registration.tsx
> Full name is required when registration

- frontend/src/components/Promotional/ProductHeader.tsx
- frontend/src/pages/GroupPage.tsx
- frontend/src/pages/GroupsListPage.tsx
fixed issues caused by groups not having a banner and changing hooks order.
> 208 blank screen when trying to join public group

- frontend/src/pages/Registration.tsx
Added checking for registration inputs
full name should be at least 1 character
email should follow email format (e.g. * @ * . *)
password needs to be at least 6 characters
resolves #266
> Added checking for registration

- frontend/src/components/FileDropzone.tsx
Simple change to provide users feedback when they upload a photo.
Resolves #190
> Upload confirmation

- frontend/src/firebase/firebase.tsx
- frontend/src/pages/Registration.tsx
Adding toast notifications to handle error states when logging in and registering. All calls to react "alert" have been replaced.
Resolves #257
> Adding better error handling for authentication

- frontend/src/components/Header.tsx
- frontend/src/components/Profiles/AddCar.tsx
- frontend/src/components/Profiles/CarStatsSlider.tsx
- frontend/src/components/Profiles/ManageCars.tsx
- frontend/src/firebase/database.tsx
- frontend/src/theme/components/button.tsx
Changes:
- Cars have unique ids now
- users can modify or delete their cars
Resolves #160
> Manage cars

- frontend/src/firebase/database.tsx
- frontend/src/pages/CreateGroup.tsx
Implemented my original intent of adding of an incrementing number to the ID, and thus URL, of conflicting Group names.
For example, multiple "My Group" names result in IDs: my-group, my-group1, my-group2, ..., my-group10, ...
One potential issue is one user being a member in two groups with identical names and having a confusing Group List, but this seems highly unlikely and could be alleviated with profile pictures.
Closes #271 if we're happy with this solution.
> Increment Group IDs on conflict

- frontend/src/components/Rides/CompleteRideButton.tsx
- frontend/src/components/Rides/RideCard.tsx
Ride completion now uses a Charka-UI Alert Diolog instead of a react `success` component.
resolves #298
> Converting ride completion to use Charka Alert Dialog

- frontend/src/components/FileDropzone.tsx
- frontend/src/components/Groups/GroupDrawer.tsx
- frontend/src/components/Groups/GroupSearch.tsx
- frontend/src/components/Promotional/PricingCard.tsx
- frontend/src/pages/GroupPage.tsx
- frontend/src/theme/colours.tsx
- frontend/src/theme/components/input.tsx
Fixing all issues in dark theme that made text unreadable. I tried my best to make the dark theme look good too but it could probably use another pass in the future.
- Cleaned up the appearance of the "group description" on both themes.
- Fixed input colors.
- File upload colors.
- Pricing cards colors.
- Many more color fixes.
Resolves #290
> Fixing all major dark-theme style issues

- frontend/public/index.html
- frontend/src/App.tsx
- frontend/src/pages/GroupPage.tsx
Instead of loading the entire application on initial load, this makes the pages load individually. This makes going between pages no longer instant - but time to first paint *much* faster.
> Bundle optimizations

- frontend/src/components/Rides/CompleteRideButton.tsx
- frontend/src/components/Rides/RideCard.tsx
hided all the buttons that shouldn't be in previous rides
also changed their colors to light grey
resolve #303
> Fixed complete ride bug

- frontend/src/components/Groups/IconBrowser.tsx
- frontend/src/components/VerifiedStep.tsx
- frontend/src/theme/components/button.tsx
> Next and prev buttons moved for better UX. Icon sizes changed.

- frontend/src/components/Rides/GasCalculator.tsx
> Added tooltip for gas calculation

- frontend/src/pages/CreateRide.tsx
Replace onDrag functions with anonymous functions and add startPosition and endPosition to the dependancies of the Map bounds invalidation effect.
Closes #297
> Update CreateRide map bounds on position change

- frontend/src/components/Promotional/PriceSelector.tsx
- frontend/src/components/Promotional/PricingCard.tsx
We have decided to remove the option to create a premium group for the Milestone 3 demo. As such, I have removed the "select" button and added a banner to indicate that those plans are coming soon.
Resolves #335
> Disabling Paid Plans

- frontend/src/components/Rides/GasCalculator.tsx
- frontend/src/components/Rides/RideCard.tsx
Fixing various ride style issues, mostly in dark mode.
- Changed gas calculator info icon
- Changed dark mode colours
- Better border style and radius
Resolves #315
> Dark mode rides

- frontend/src/components/Header.tsx
- frontend/src/pages/CreateGroup.tsx
- frontend/src/pages/CreateRide.tsx
- frontend/src/pages/JoinGroup.tsx
Since we are slowly converging on a single page app I have removed breadcrumbs and added a "home" button to get back to the main screen.
Resolves #321
> Removing breadcrumbs, adding home button

- frontend/src/firebase/firebase.tsx
- Fixing the toast notifications on the login screen so that they do not change the theme. Apparently you need to pass the theme to the toast notifications if you have overridden the theme.
- Making all toast notifications closable.
Resolves #317
> Fixing toast bug

- frontend/src/components/ColorModeSwitcher.tsx
- frontend/src/pages/LoginPage.tsx
- frontend/src/pages/Registration.tsx
Fixed dark theme issue in Login and Registration pages
Fixed dark theme button placement issue
Resolves #344
Resolves #345
> dark theme for login and register pages

- frontend/src/components/Groups/GroupSettings.tsx
- frontend/src/components/Promotional/Card.tsx
- frontend/src/firebase/firebase.tsx
- frontend/src/pages/LoginPage.tsx
- frontend/src/pages/ProductPage.tsx
- frontend/src/theme/colours.tsx
- frontend/src/theme/style.tsx
Setting the default theme based on system settings and some product page style fixes in dark mode.
Resolves #318
> Dark theme final changes

- frontend/src/Directions.tsx
- frontend/src/components/Rides/AddPickupPoint.tsx
- frontend/src/components/Rides/PickupMarkers.tsx
- frontend/src/components/Rides/RideCard.tsx
- frontend/src/firebase/database.tsx
Closes #216.
Duration and distance between points is now taken with the Route from MQ, then calculated to be cumulative from the start.
Pickup Point popups now show the Pickup Time from start time on them.
Will add new issue to style map markers to show times directly.
> Show Estimated Pickup Times

- frontend/src/components/Header.tsx
I can use some feedback on wording here:
Does it look okay?
resolves #334
> Added report a bug button

- frontend/src/components/Header.tsx
- frontend/src/components/Promotional/LogoName.tsx
- frontend/src/components/Promotional/ProductHeader.tsx
I turned the logo/name combo from the product page into a component that is now always in the header. I added a badge to that component that shows that the product is in beta.
Resolves #352
> Obvious Beta Status

- frontend/src/App.tsx
- frontend/src/NavigationConstants.ts
- frontend/src/components/Groups/GroupSearch.tsx
- frontend/src/components/Groups/GroupSelector.tsx
- frontend/src/pages/GroupPage.tsx
- frontend/src/pages/LoginPage.tsx
- frontend/src/pages/Registration.tsx
Overhauled the way that routing works with auth, please try to break the redirect being authorized and unauthorized.
I also fixed a bunch of sudden jumps that occur when loading the app. This includes but is not limited to:
- Making the banner pre-fill with a transparent box of the same size as the banner.
- Making the group selector the same size before the groups load in.
- The auth redirect fixes also prevent the product page from being rendered briefly when a group page loads.
- Resolves #311
> Fixing Loading

- frontend/src/components/PasswordField.tsx
- frontend/src/pages/LoginPage.tsx
- frontend/src/pages/Registration.tsx
- frontend/src/theme/components/button.tsx
- frontend/src/theme/components/input.tsx
Registration page: 
* made input field more visible in dark mode, 
* create account button now visible in dark mode
Login Page:
* reset password modal fixed (margin on the bottom, position of button) 
resolves #377
> styling in registration & login page

- frontend/src/pages/CreateGroup.tsx
Adding a new step to the group creation for setting group publicity.
Fixing padding
Resolves #390
> Create group style

- frontend/src/components/Header.tsx
- frontend/src/components/Profiles/AddCar.tsx
- frontend/src/components/Profiles/ManageCars.tsx
- frontend/src/components/Tutorial.tsx
- frontend/src/pages/CreateRide.tsx
- frontend/src/theme/colours.tsx
- frontend/src/theme/components/button.tsx
Create a Ride page:
* changed wording
* changed colors of the buttons
* defined "checkmark green" in style page
Add a car modal:
* Everything is now a VerifiedStep
Manage Cars:
* Deleted Cancel button
Report a bug:
* Adjusted padding a little bit
> Ride fixes

- frontend/src/components/Header.tsx
- frontend/src/pages/CreateGroup.tsx
- frontend/src/pages/CreateRide.tsx
- frontend/src/pages/JoinGroup.tsx
- frontend/src/pages/WelcomePage.tsx
Removing the "Home" button and move its functionality to the Tandem Logo in the header.
Fixing where the home button redirects to.
Resolves #397
> Home button fixes

- frontend/src/pages/LoginPage.tsx
- frontend/src/pages/Registration.tsx
Fixing the size of the login/register page background so the bg colour always takes up 100% of the screen.
Resolves #409
> Fixing short background bug

- frontend/src/components/Profiles/CarStatsSlider.tsx
Removing gas minimum in car stats slider.
> Simple fix removing the minimum gas amount.

- frontend/src/components/Promotional/ProductHeader.tsx
- frontend/src/theme/components/menu.tsx
- frontend/src/theme/style.tsx
Product Page below `md` breakpoint now has a larger, white hamburger that opens a menu with grouped links and Login and Register at the top.
Thoughts?
> Change ProductPage Hamburger to open Menu

- frontend/src/components/Groups/GroupSelector.tsx
- frontend/src/components/Tutorial.tsx
- frontend/src/pages/WelcomePage.tsx
Fixing the welcome tutorial on mobile.
Making all tutorials repeatable.
Resolves #380
> Tutorial Fixes

- frontend/src/components/Header.tsx
- frontend/src/components/Profiles/AddCar.tsx
- frontend/src/pages/CreateRide.tsx
* Changed the wording on "Report a Bug" modal
* Gave some padding on "Create a Ride" Heading
* Changed the default value of "Add a Car" from Two-seater to Compact 
Resolves #426
> Fixed report a bug wording

- frontend/src/components/Groups/GroupInfo.tsx
- frontend/src/components/Rides/GasCalculator.tsx
- frontend/src/components/Rides/RideCard.tsx
- frontend/src/components/Tutorial.tsx
- frontend/src/pages/GroupPage.tsx
> removed border from gas calculator

- frontend/src/components/Promotional/ProductHeader.tsx
- frontend/src/components/Rides/CompleteRideButton.tsx
- frontend/src/components/Rides/LocationSearch.tsx
- frontend/src/components/Rides/RideCard.tsx
- frontend/src/pages/GroupPage.tsx
Fixing ride card spacing and weird size changes on mobile also fixed. Resolves #431
> 431 fixing product page mobile menu colours light mode

- frontend/src/Directions.tsx
- frontend/src/components/Groups/GroupInfo.tsx
- frontend/src/components/Groups/GroupSelector.tsx
- frontend/src/pages/LoginPage.tsx
Removing console.log statements
Fixing leave group
> Leave groups redirect
