CobeyH/SENG-480A

.github/workflows/backend.yml
backend/README.md
backend/build.gradle.kts
backend/src/main/kotlin/Main.kt
backend/src/main/kotlin/TokenAuthenticator.kt
backend/src/test/kotlin/TokenAuthenticatorKtTest.kt
backend/src/test/kotlin/TokenAuthenticatorTest.kt
backend/src/test/resources/junit-platform.properties
gradle.properties

Resolves #2 by setting up authentication on the backend. Also added docs to alleviate a potentially confusing error message (we cannot check in the service account key, so everyone needs to get thier own.) The code documentation in [TokenAuthenticator](https://github.com/CobeyH/SENG-480A/blob/021bf55a7e30f56b0117bbb96e7f1b0f6671e467/backend/src/main/kotlin/TokenAuthenticator.kt) is *not* a standard I want to set, but hopfully makes the code super clear while http4k and kotlin are potentially new. I've also updated [Main](https://github.com/CobeyH/SENG-480A/blob/021bf55a7e30f56b0117bbb96e7f1b0f6671e467/backend/src/main/kotlin/Main.kt) with an authenticated `greet` endpoint to showcase routing and authentication.
Still to do

Authentication

---

frontend/package-lock.json
frontend/package.json
frontend/src/firebase.tsx
frontend/src/pages/CreateGroup.tsx
frontend/src/pages/CreateRide.tsx
frontend/src/pages/GroupPage.tsx
frontend/src/pages/GroupsListPage.tsx
frontend/src/pages/JoinGroup.tsx
frontend/src/pages/RidePage.tsx

When a Group or Ride is created it is stored under an id based on its title:
- `Erin's Surfer Group => erins-surfer-group`
- `Tofino Weekend => tofino-weekend`
During Ride creation they are stored under their Group's `rides` sub-collection and users are redirected to the Group page, not the Ride page.
Database Types are refactored to be in their respective `Create<Type>.tsx` and imported elsewhere.
Closes #51 and #38.

Created Rides and Groups use title-slug IDs and are now linked

---

frontend/src/pages/CreateRide.tsx

Simple fix for map error. If the user doesn't move the destination icon on Create Ride page, they can't click 'create' button so that they don't end up with (0,0) coordinate as their destination 
Resolves #46

Fix map error (#46)

---

frontend/firebase.json

Fixing some very obscure issues that only affect macOS Monterey when running Node 17 and firebase emulators that took me a while to figure out.
Summary: the latest version of macOS rewrites localhost to ipv6 address `::1` instead of `127.0.0.1` as it has always been, and firebase emulators don't expect that and timeout waiting for their requested ports. Also macOS now uses port 5000 for AirPlay despite its popular use by developer tools.
Further reading: [Firebase Localhost Issue](https://github.com/firebase/firebase-tools/issues/2379) and [macOS port issue](https://chrishannah.me/monterey-blocking-ports-5000-and-7000/)

Fix macOS Monterey obscure bugs

---

frontend/src/components/RideCard.tsx
frontend/src/pages/CreateRide.tsx

Generating IDs for rides automatically using Firebase `Push` function. This means that rides and groups can have the same name and prevents race conditions if two people make a ride with the same name at the same time.
Resolves #54

Unique automatic ride Id generation

---

frontend/src/components/GroupCapacity.tsx
frontend/src/components/GroupJoinButton.tsx
frontend/src/components/GroupMembersList.tsx
frontend/src/components/GroupSearch.tsx
frontend/src/components/GroupSettings.tsx
frontend/src/components/GroupSizeSlider.tsx
frontend/src/firebase/database.tsx
frontend/src/pages/CreateGroup.tsx
frontend/src/pages/GroupPage.tsx

Adding a slider to the `CreateGroup` page to set the maximum number of people in a group.
- When viewing groups on the `GroupList` modal you can see how full they are.
- Groups that are full cannot be joined
- Added a settings page to groups where owners can edit the member capacity of their group.
Resolves #91

Premium groups

---

frontend/src/components/ChooseCar.tsx
frontend/src/pages/CreateGroup.tsx
frontend/src/pages/CreateRide.tsx

Fixing several minor issues from user feedback.
The "submit" button on the create ride page now switched from grey to blue when all required information is provided.
The "select car" select component now provides a quick link to add a car if they don't have any. This doesn't look great but it's better than nothing.
Adding helptext to explain what a private group is.
Resolves #202

Easy add car

---

frontend/src/components/Groups/ShareLink.tsx
frontend/src/pages/GroupPage.tsx

Adding a message such as "Cobey Hollier invited you to join their Tandem group! Follow the link to join the group: http://localhost:3000/group/public-chatting/join" when you click the "Share Link" button.
Sorry @samanthamhill but we cannot support emojis.
Resolves #212

Better context for share links

---

frontend/src/components/Groups/IconBrowser.tsx
frontend/src/components/VerifiedStep.tsx
frontend/src/pages/CreateGroup.tsx
frontend/src/pages/GroupsListPage.tsx

Creating this on behalf on Sam since she is busy today. 
You can now use an Icon as a profile picture instead of uploading a picture. There is a search box to help users find the right icon for their use-case.
Resolves #217

217 profile icons instead of pictures

---

frontend/src/components/Groups/GroupJoinButton.tsx
frontend/src/components/Groups/GroupSearch.tsx
frontend/src/components/Promotional/PriceSelector.tsx
frontend/src/pages/GroupsListPage.tsx
frontend/src/pages/JoinGroup.tsx

Adding a button to the group search list that allows the user to see a preview of the group before joining it. Also adding a Chakra Alert to the preview page when the group is full so that users don't get confused by the disabled button.
I haven't touched the "Join Group Page" contents since that is a separate issue.
Resolves #259

Public Group Preview

---

frontend/src/components/Promotional/PriceSelector.tsx
frontend/src/pages/CreateGroup.tsx

The max width of the "Create Group" page was too skinny to display the price selector. This resulted in it looking bad. I also thought that the "select" buttons disappearing when the plan was selected looked weird. It looked like this before 
And now it looks like this.

Fixing price selector width in create group

---

frontend/src/pages/CreateRide.tsx

In user testing somebody reported that the "time selection" when creating a ride seemed broken. I made the time input default to the current time so that it's obvious what you're meant to type to edit the time.
Resolves #291

Trying to make the time selection obviously not-broken

---

frontend/src/components/Promotional/Quotee.tsx
frontend/src/components/Promotional/Testimonial.tsx
frontend/src/pages/GroupPage.tsx
frontend/src/pages/GroupsListPage.tsx

Fixing numerous console errors on the Production, Group List, and Group pages. There are probably still errors in other components, but I fixed a bunch of the main pages.
Fixes include:
- Invalid download url refs for profile pictures
- Errors when loading icon profile pictures
- imgsrc on client testimonials
- Fixing group list navigation error
Resolves #293

Fixing errors on promotion, group list and group page.

---

frontend/src/components/Groups/GroupSearch.tsx

Improving UX in the "Public Group Search" so that a message is displayed if their search query returned no groups. It gives them a helpful message and a quick link to create their own group.
Resolves #294

Adding message if search has no results

---

frontend/src/components/Profiles/CarStatsSlider.tsx
frontend/src/pages/GroupPage.tsx

Simple fix adding helptext to the number of seats slider for better clarity.
I also made another simple change to hide the group description if it's empty (no box gets rendered).
Resolves #289

Adding help-text explaining that num-seats includes driver

---

frontend/src/firebase/firebase.tsx

This should handle the error where you sign up with Google and then try to sign up with Facebook. Could somebody who has a Facebook account that is registered using a gmail address please test it? Such as @samanthamhill 
Resolves #276

Handing duplicate auth provider error

---

frontend/src/components/Groups/GroupSelector.tsx

Really simple fix making the group list static so that it doesn't scroll with the page.
Resolves #331

 Making group list float

---

frontend/src/components/Groups/GroupSelector.tsx

I just checked how a bunch of mobile apps handle this problem. Almost universally they have a small header at the top that floats at the top of the page when you scroll. All the important buttons such as the groups list, chat, etc are on the header and don't overlap with anything since they are on the header.
Resolves #330

Fixing group list overlap mobile

---

frontend/src/components/Profiles/AddCar.tsx
frontend/src/components/Rides/ChooseCar.tsx
frontend/src/components/Rides/RideCard.tsx

Resolves #310 
There are several tricky edge cases that this bug has to consider which should all work as expected now.
1. The ride in the database should not be updated until a car is selected. There should be NO way to become the driver in the database without an associated car (they will appear to be the driver but it won't persist if they don't add a car).
2. If the user joins and already has a car then the ride should automatically select their first car and update the database with them as the driver.
3. If a driver joins without a car then they will be presented with an option to add a car. If they reload the page instead of adding a car then the "Driver" toggle will be reset so they aren't the driver.
4. If a driver joins without a car and then adds a car they can immediately …

Fixing driver joining ride without a car bug

---

frontend/src/components/FileDropzone.tsx
frontend/src/components/Groups/GroupSelector.tsx
frontend/src/pages/GroupPage.tsx

Fixing the scrolling behaviour and overlap of the `Group Selector` component on the Welcome and Group pages. The group selector now starts below the header and scrolls up until the header goes off screen. Then the group selector stops scrolling.
Test it on the welcome page, on a group page with a banner, and a group page without a banner.
Resolves #355

Group selector overlap

---

frontend/src/components/Groups/GroupCapacity.tsx
frontend/src/components/Groups/GroupSearch.tsx

Cleaning up the styling on the group search modal.
Added dynamic sizing for different sized screens.
Fixed the alignment and padding issues
Replaced the group capacity with a colour indicator of how full the group is. It shows green if the group is mostly empty, yellow if the group is half full and red if the group is full.
Resolves #357

Fixing group search styling

---

frontend/src/components/Groups/Chat.tsx

Adding an icon to the chat input as an alternative to the "return" key.
Also adding a placeholder for consistency with other inputs.
Resolves #394

Chat send icon

---

frontend/src/components/Groups/GroupSelector.tsx
frontend/src/theme/components/button.tsx

Closes #392 
Used paleBlue for hover and darkBlue for current, can be changed.

Add Indicators to GroupSelectorElements

---

frontend/src/pages/GroupPage.tsx

Fixing the way that rides are grouped.
Added a switch to show/hide the previous rides. They could get pretty long if a group gets old so they shouldn't be so easy to access.
Resolves #402

Ride groupings

---

frontend/src/components/Groups/ShareLink.tsx
frontend/src/components/Header.tsx
frontend/src/pages/CreateGroup.tsx

Fixing issues where the user's name would display as "null". Including group share link and settings page.
Resolves #381

Fixing null user name in sharelink and settings page

---

frontend/src/pages/CreateRide.tsx

Allow the user to proceed past the "start time" step in create ride using the default time.
Firefox doesn't have the small clock or calendar icons to the right of the input so I don't know how to fix the colour of those.
Resolves #399

Allowing default time

---

frontend/src/components/Groups/GroupInfo.tsx

Fixing modal content width
